model:
  image_dim: 28
  fovea_radius: 2
  patch_dim: 8
  patch_channels: 1
  num_steps: 4
  ladder_dims:
  - 25
  z_dims:
  - 10
  ladder_hidden_dims:
  - - 256
    - 256
  lvae_inf_hidden_dims:
  - - 256
    - 256
  lvae_gen_hidden_dims:
  - - 256
    - 256
  npp_embed_dim: 256
  npp_hidden_dim: 512
  npp_num_heads: 1
  npp_num_layers: 3
  foveation_padding: max
  foveation_padding_mode: replicate
  lr: 0.001
  betas:
    curr_patch_recon: 1
    curr_patch_kl: 1
    next_patch_pos_kl: 1
    next_patch_recon: 1
    next_patch_kl: 1
    image_recon: 1
    spectral_norm: 0
  free_bits_kl: 0.5
  grad_skip_threshold: -1
  do_batch_norm: false
  # do_use_beta_norm: false
  frac_random_foveation: 0.0
  do_image_reconstruction: true
  do_next_patch_prediction: true
  reconstruct_fovea_only: false
  do_lateral_connections: true
  do_sigmoid_next_location: false
  npp_do_mask_to_last_step: false
  npp_do_flag_last_step: false
  image_reconstruction_frac: 0.1
