trainer:
  logger: true
  enable_checkpointing: true
  gradient_clip_val: 100
  track_grad_norm: 2
  check_val_every_n_epoch: 1
  max_epochs: 3000
  log_every_n_steps: 10
  accelerator: auto
  enable_model_summary: true
  num_sanity_val_steps: 2
  reload_dataloaders_every_n_epochs: 10
  strategy: ddp
  # defaults:
  callbacks: null
  default_root_dir: null
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  devices: null
  gpus: null
  auto_select_gpus: null
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  fast_dev_run: false
  accumulate_grad_batches: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  sync_batchnorm: false
  precision: 32
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: null
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: null
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  inference_mode: true
